export const employeeData = [
    {
      id: 1,
      name: 'Esther Howard',
      position: "Sale's manager USA",
      transactions: 3490,
      rise: true,
      tasksCompleted: 3,
      imgId: 0,
    },
  
    {
      id: 2,
      name: 'Eleanor Pena',
      position: "Sale's manager Europe",
      transactions: 590,
      rise: false,
      tasksCompleted: 5,
      imgId: 2,
    },
  
    {
      id: 3,
      name: 'Robert Fox',
      position: "Sale's manager Asia",
      transactions: 2600,
      rise: true,
      tasksCompleted: 1,
      imgId: 3,
    },
  ];
  
  export  const Countrydata = [
    { name: 'USA', rise: true, value: 21942.83, id: 1 },
    { name: 'Ireland', rise: false, value: 19710.0, id: 2 },
    { name: 'Ukraine', rise: false, value: 12320.3, id: 3 },
    { name: 'Sweden', rise: true, value: 9725.0, id: 4 },
  ];
  export const segmentationData = [
    { c1: 'Not Specified', c2: '800', c3: '#363636', color: '#535353' },
    { c1: 'Male', c2: '441', c3: '#818bb1', color: '#595f77' },
    { c1: 'Female', c2: '233', c3: '#2c365d', color: '#232942' },
    { c1: 'Other', c2: '126', c3: '#334ed8', color: '#2c3051' },
  ];
  
  export const sidebarItems = [
    [
      { id: '0', title: 'Dashboard', notifications: false, route: "/", parent: "/home" },
    ],
    [
      {
        id: '1', title: 'Customer', notifications: false, route: "/customer", parent: "/customer", dropdownItems: [
          { id: '1-1', title: "Add Customer", route: "/customer/add" },
          { id: '1-2', title: "List Customer", route: "/customer" },
          { id: '1-3', title: "Customer Category", route: "/customer/category" },
          { id: '1-4', title: "Contacts", route: "/customer/contacts" }
        ]
      },
      {
        id: '2', title: 'Vendor', notifications: false, route: "/vendor", parent: "/vendor", dropdownItems: [
          { id: '2-1', title: "Add Vendor", route: "/vendor/add" },
          { id: '2-2', title: "List Vendor", route: "/vendor/list" },
          { id: '2-3', title: "Vendor Category", route: "/vendor/category" },
          { id: '2-4', title: "Contacts", route: "/vendor/contacts" }
        ]
      },
      {
        id: '3', title: 'Product', notifications: false, route: "/product", parent: "/product", dropdownItems: [
          { id: '3-1', title: "Add Products", route: "/product/add" },
          { id: '3-2', title: "List Products", route: "/product/list" },
          { id: '3-3', title: "Product Category", route: "/product/category" },
          { id: '3-4', title: "Prices", route: "/product/prices" },
          { id: '3-5', title: "Inventory", route: "/product/inventory" }
        ]
      },
      {
        id: '4', title: 'Services', notifications: false, route: "/services", parent: "/services", dropdownItems: [
          { id: '4-1', title: "Service Category", route: "/services/category" },
          { id: '4-2', title: "Add Services", route: "/services/add" },
          { id: '4-3', title: "List Services", route: "/services/list" },
          { id: '4-4', title: "Prices", route: "/services/prices" }
        ]
      },
      {
        id: '5', title: 'Pre-Sales', notifications: false, route: "/presales", parent: "/presales", dropdownItems: [
          { id: '5-1', title: "Add Quotes", route: "/presales/quotes/add" },
          { id: '5-2', title: "View Quotes", route: "/presales/quotes/view" },
          { id: '5-3', title: "Add Enquiry", route: "/presales/enquiry/add" },
          { id: '5-4', title: "List Enquiry", route: "/presales/enquiry/list" },
          { id: '5-5', title: "Add Purchase Order", route: "/presales/purchaseorder/add" },
          { id: '5-6', title: "List Purchase Order", route: "/presales/purchaseorder/list" },
          { id: '5-7', title: "Add Delivery Note", route: "/presales/deliverynote/add" },
          { id: '5-8', title: "List Delivery Note", route: "/presales/deliverynote/list" }
        ]
      },
      {
        id: '6', title: 'Delivery', notifications: false, route: "/delivery", parent: "/delivery", dropdownItems: [
          { id: '6-1', title: "Shipping Carrier", route: "/delivery/shippingcarrier" },
          { id: '6-2', title: "Logistic Management", route: "/delivery/logisticmanagement" },
          { id: '6-3', title: "Delivery By Owner", route: "/delivery/byowner" },
          { id: '6-4', title: "Tracking", route: "/delivery/tracking" }
        ]
      },
      {
        id: '7', title: 'Store', notifications: false, route: "/store", parent: "/store", dropdownItems: [
          {
            id: '7-1', title: "Order Management", route: "/store/ordermanagement", dropdownItems: [
              { id: '7-1-1', title: "Add Orders", route: "/store/ordermanagement/add" },
              { id: '7-1-2', title: "List Orders", route: "/store/ordermanagement/list" },
              { id: '7-1-3', title: "Cancel Orders", route: "/store/ordermanagement/cancel" },
              { id: '7-1-4', title: "Refund", route: "/store/ordermanagement/refund" }
            ]
          },
          {
            id: '7-2', title: "RFQ", route: "/store/rfq", dropdownItems: [
              { id: '7-2-1', title: "Add RFQ", route: "/store/rfq/add" },
              { id: '7-2-2', title: "View RFQ", route: "/store/rfq/view" },
              { id: '7-2-3', title: "Cancel", route: "/store/rfq/cancel" },
              { id: '7-2-4', title: "Send RFQ", route: "/store/rfq/send" }
            ]
          },
          {
            id: '7-3', title: "App Management", route: "/store/appmanagement", dropdownItems: [
              { id: '7-3-1', title: "Geo-Blocking", route: "/store/appmanagement/geoblocking" },
              { id: '7-3-2', title: "Layout", route: "/store/appmanagement/layout" },
              { id: '7-3-3', title: "Menu", route: "/store/appmanagement/menu" },
              { id: '7-3-4', title: "Payment Configuration", route: "/store/appmanagement/paymentconfig" },
              { id: '7-3-5', title: "Mail Template", route: "/store/appmanagement/mailtemplate" },
              { id: '7-3-6', title: "Branding And Themes", route: "/store/appmanagement/branding" }
            ]
          },
          {
            id: '7-4', title: "Payment", route: "/store/payment", dropdownItems: [
              { id: '7-4-1', title: "List Payments", route: "/store/payment/list" },
              { id: '7-4-2', title: "Cancel Payments", route: "/store/payment/cancel" },
              { id: '7-4-3', title: "Refund", route: "/store/payment/refund" }
            ]
          }
        ]
      },
      {
        id: '8', title: 'Reporting And Analytics', notifications: false, route: "/reporting", parent: "/reporting", dropdownItems: [
          { id: '8-1', title: "Reports", route: "/reporting/reports" },
          { id: '8-2', title: "Analytics", route: "/reporting/analytics" }
        ]
      },
      {
        id: '9', title: 'Admin And Security', notifications: false, route: "/admin", parent: "/admin", dropdownItems: [
          { id: '9-1', title: "Organization", route: "/admin/organization" },
          { id: '9-2', title: "Teams", route: "/admin/teams" },
          { id: '9-3', title: "Add User", route: "/admin/adduser" },
          { id: '9-4', title: "View User", route: "/admin/viewuser" },
          { id: '9-5', title: "User Permission", route: "/admin/userpermission" },
          { id: '9-6', title: "Login Info", route: "/admin/logininfo" },
          { id: '9-7', title: "Logs", route: "/admin/logs" }
        ]
      }
    ],
  ];
  
  

  export const industries = [
    'Aerospace and Defense',
    'Automotive',
    'Banking',
    'Biotechnology',
    'Chemical',
    'Construction',
    'Consumer Electronics',
    'Education',
    'Energy',
    'Entertainment',
    'Fashion',
    'Financial Services',
    'Food and Beverage',
    'Healthcare',
    'Information Technology',
    'Insurance',
    'Manufacturing',
    'Media',
    'Mining',
    'Pharmaceuticals',
    'Real Estate',
    'Retail',
    'Telecommunications',
    'Transportation',
    'Utilities',
    'Accounting',
    'Advertising',
    'Agriculture',
    'Architecture',
    'Automotive Repair',
    'Aviation',
    'Beauty and Cosmetics',
    'Broadcasting',
    'Computer Games',
    'Computer Hardware',
    'Computer Software',
    'Consulting',
    'Consumer Goods',
    'Courier Services',
    'E-commerce',
    'Education Management',
    'Electrical/Electronic Manufacturing',
    'Facilities Services',
    'Farming',
    'Financial Planning',
    'Fishery',
    'Fundraising',
    'Furniture',
    'Glass, Ceramics & Concrete',
    'Government Administration',
    'Graphic Design',
    'Higher Education',
    'Hospitality',
    'Human Resources',
    'Individual and Family Services',
    'Industrial Automation',
    'Information Services',
    'Information Technology and Services',
    'Insurance',
    'International Trade and Development',
    'Internet',
    'Investment Banking',
    'Judiciary',
    'Law Enforcement',
    'Legal Services',
    'Leisure, Travel & Tourism',
    'Libraries',
    'Logistics and Supply Chain',
    'Luxury Goods & Jewelry',
    'Machinery',
    'Management Consulting',
    'Maritime',
    'Marketing and Advertising',
    'Market Research',
    'Mechanical or Industrial Engineering',
    'Medical Devices',
    'Medical Practice',
    'Mining & Metals',
    'Nonprofit Organization Management',
    'Nursing',
    'Oil & Energy',
    'Online Media',
    'Outsourcing/Offshoring',
    'Package/Freight Delivery',
    'Packaging and Containers',
    'Paper & Forest Products',
    'Performing Arts',
    'Pharmaceuticals',
    'Photography',
    'Plastics',
    'Political Organization',
    'Primary/Secondary Education',
    'Printing',
    'Professional Training',
    'Program Development',
    'Public Relations',
    'Public Safety',
    'Publishing',
    'Railroad Manufacture',
    'Ranching',
    'Real Estate',
    'Religious Institutions',
    'Renewables & Environment',
    'Research',
    'Restaurants',
    'Retail',
    'Security and Investigations',
    'Semiconductors',
    'Shipbuilding',
    'Sporting Goods',
    'Sports',
    'Staffing and Recruiting',
    'Supermarkets',
    'Telecommunications',
    'Textiles',
    'Think Tanks',
    'Tobacco',
    'Translation and Localization',
    'Transportation/Trucking/Railroad',
    'Utilities',
    'Venture Capital',
    'Veterinary',
    'Warehousing',
    'Wholesale',
    'Wine and Spirits',
    'Wireless',
    'Writing and Editing',
    'Others',
    'Media',
    'Streaming',
    'OTT',
    'Gaming'
  ];
  
export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, North',
  'Korea, South',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];


export const customerDefault = {
  name: '',
  email: '',
  address: '',
  website: '',
  state: '',
  category: '',
  location: '',
  country: '',
  pan: '',
  gst: ''
}

export const categoryDefault = {
  
}

export const teamDefault = {
  teamName: ""
};

export const employeeDefault = {
    name: "",
    userId: "",
    teamId: "",
    admin: "",
    superAdmin: "",
    designation: "",
    superior: "",
    address: "",
    passport: "",
    dateOfBirth: "",
    dateOfJoining: "",
    phoneNumber: "",
    activeUser: "",
    emergencyContact: [{ name: '', phone: '', relationship: '' }]
  
}


