export const employeeData = [
    {
      id: 1,
      name: 'Esther Howard',
      position: "Sale's manager USA",
      transactions: 3490,
      rise: true,
      tasksCompleted: 3,
      imgId: 0,
    },
  
    {
      id: 2,
      name: 'Eleanor Pena',
      position: "Sale's manager Europe",
      transactions: 590,
      rise: false,
      tasksCompleted: 5,
      imgId: 2,
    },
  
    {
      id: 3,
      name: 'Robert Fox',
      position: "Sale's manager Asia",
      transactions: 2600,
      rise: true,
      tasksCompleted: 1,
      imgId: 3,
    },
  ];
  
  export  const Countrydata = [
    { name: 'USA', rise: true, value: 21942.83, id: 1 },
    { name: 'Ireland', rise: false, value: 19710.0, id: 2 },
    { name: 'Ukraine', rise: false, value: 12320.3, id: 3 },
    { name: 'Sweden', rise: true, value: 9725.0, id: 4 },
  ];
  export const segmentationData = [
    { c1: 'Not Specified', c2: '800', c3: '#363636', color: '#535353' },
    { c1: 'Male', c2: '441', c3: '#818bb1', color: '#595f77' },
    { c1: 'Female', c2: '233', c3: '#2c365d', color: '#232942' },
    { c1: 'Other', c2: '126', c3: '#334ed8', color: '#2c3051' },
  ];
  
  export const sidebarItems = [
    [
      { id: '0', title: 'Dashboard', notifications: false, route: "/", parent: "/home" },
    ],
    [
      {
        id: '1', title: 'Customer', notifications: false, route: "/customer", parent: "/customer", dropdownItems: [
          { id: '1-1', title: "Add Customer", route: "/customer/add" },
          { id: '1-2', title: "List Customer", route: "/customer" },
          { id: '1-3', title: "Customer Category", route: "/customer/category" },
          { id: '1-4', title: "Contacts", route: "/customer/contacts" }
        ]
      },
      {
        id: '2', title: 'Vendor', notifications: false, route: "/vendor", parent: "/vendor", dropdownItems: [
          { id: '2-1', title: "Add Vendor", route: "/vendor/add" },
          { id: '2-2', title: "List Vendor", route: "/vendor/list" },
          { id: '2-3', title: "Vendor Category", route: "/vendor/category" },
          { id: '2-4', title: "Contacts", route: "/vendor/contacts" }
        ]
      },
      {
        id: '3', title: 'Product', notifications: false, route: "/product", parent: "/product", dropdownItems: [
          { id: '3-1', title: "Add Products", route: "/product/add" },
          { id: '3-2', title: "List Products", route: "/product/list" },
          { id: '3-3', title: "Product Category", route: "/product/category" },
          { id: '3-4', title: "Catalog", route: "/product/catalog" },
          { id: '3-4', title: "Prices", route: "/product/prices" },
          { id: '3-5', title: "Inventory", route: "/product/inventory" }
        ]
      },
      {
        id: '4', title: 'Services', notifications: false, route: "/services", parent: "/services", dropdownItems: [
          { id: '4-1', title: "Service Category", route: "/services/category" },
          { id: '4-2', title: "Add Services", route: "/services/add" },
          { id: '4-3', title: "List Services", route: "/services/list" },
          { id: '4-4', title: "Prices", route: "/services/prices" }
        ]
      },
      {
        id: '5', title: 'Pre-Sales', notifications: false, route: "/presales", parent: "/presales", dropdownItems: [
          // { id: '5-1', title: "Add Quotes", route: "/presales/quotes/add" },
          { id: '5-2', title: "Quotes", route: "/presales/quotes/view" },
          // { id: '5-3', title: "Add Enquiry", route: "/presales/enquiry/add" },
          { id: '5-4', title: "Enquiry", route: "/presales/enquiry/list" },
          { id: '5-5', title: "Add Purchase Order", route: "/presales/purchaseorder/add" },
          { id: '5-6', title: "List Purchase Order", route: "/presales/purchaseorder/list" },
          { id: '5-7', title: "Add Delivery Note", route: "/presales/deliverynote/add" },
          { id: '5-8', title: "List Delivery Note", route: "/presales/deliverynote/list" }
        ]
      },
      {
        id: '6', title: 'Delivery', notifications: false, route: "/delivery", parent: "/delivery", dropdownItems: [
          { id: '6-1', title: "Shipping Carrier", route: "/delivery/shippingcarrier" },
          { id: '6-2', title: "Logistic Management", route: "/delivery/logisticmanagement" },
          { id: '6-3', title: "Delivery By Owner", route: "/delivery/byowner" },
          { id: '6-4', title: "Tracking", route: "/delivery/tracking" }
        ]
      },
      {
        id: '7', title: 'Store', notifications: false, route: "/store", parent: "/store", dropdownItems: [
          {
            id: '7-1', title: "Order Management", route: "/store/ordermanagement", dropdownItems: [
              { id: '7-1-1', title: "Add Orders", route: "/store/ordermanagement/add" },
              { id: '7-1-2', title: "List Orders", route: "/store/ordermanagement/list" },
              { id: '7-1-3', title: "Cancel Orders", route: "/store/ordermanagement/cancel" },
              { id: '7-1-4', title: "Refund", route: "/store/ordermanagement/refund" }
            ]
          },
          {
            id: '7-2', title: "RFQ", route: "/store/rfq", dropdownItems: [
              { id: '7-2-1', title: "Add RFQ", route: "/store/rfq/add" },
              { id: '7-2-2', title: "View RFQ", route: "/store/rfq/view" },
              { id: '7-2-3', title: "Cancel", route: "/store/rfq/cancel" },
              { id: '7-2-4', title: "Send RFQ", route: "/store/rfq/send" }
            ]
          },
          {
            id: '7-3', title: "App Management", route: "/store/appmanagement", dropdownItems: [
              { id: '7-3-1', title: "View Setting", route: "/store/appmanagement/appsetting", dropdownItems: [
                  { id: '1-1', title: "Add Setting", route: "/store/appmanagement/appsetting/add" },
                  { id: '1-2', title: "List Settings", route: "/store/appmanagement/appsetting/list" },
                ]
              },
              { id: '7-3-1', title: "Element", route: "/store/appmanagement/element" },
              { id: '7-3-1', title: "Container", route: "/store/appmanagement/container" },
              { id: '7-3-1', title: "Page", route: "/store/appmanagement/page" },
              { id: '7-3-2', title: "Layout", route: "/store/appmanagement/layout" },
              { id: '7-3-3', title: "Menu", route: "/store/appmanagement/menu" },
              { id: '7-3-4', title: "Payment Configuration", route: "/store/appmanagement/paymentconfig" },
              { id: '7-3-5', title: "Mail Template", route: "/store/appmanagement/mailtemplate" },
              { id: '7-3-6', title: "Branding And Themes", route: "/store/appmanagement/branding" }
            ]
          },
          {
            id: '7-4', title: "Payment", route: "/store/payment", dropdownItems: [
              { id: '7-4-1', title: "List Payments", route: "/store/payment/list" },
              { id: '7-4-2', title: "Cancel Payments", route: "/store/payment/cancel" },
              { id: '7-4-3', title: "Refund", route: "/store/payment/refund" }
            ]
          },
          {
            id: '7-4', title: "Color Scheme", route: "/store/color", dropdownItems: [
              { id: '7-4-1', title: "Add Color Scheme", route: "/store/color/add" },
              { id: '7-4-2', title: "List Color Scheme", route: "/store/color/list" }
              
            ]
          }
        ]
      },
      {
        id: '8', title: 'Reporting And Analytics', notifications: false, route: "/reporting", parent: "/reporting", dropdownItems: [
          { id: '8-1', title: "Reports", route: "/reporting/reports" },
          { id: '8-2', title: "Analytics", route: "/reporting/analytics" }
        ]
      },
      {
        id: '9', title: 'Admin And Security', notifications: false, route: "/admin", parent: "/admin", dropdownItems: [
          { id: '9-1', title: "Organization", route: "/admin/organization" },
          { id: '9-2', title: "Teams", route: "/admin/teams" },
          { id: '9-3', title: "Add User", route: "/admin/adduser" },
          { id: '9-4', title: "View User", route: "/admin/viewuser" },
          { id: '9-5', title: "User Permission", route: "/admin/userpermission" },
          { id: '9-6', title: "Login Info", route: "/admin/logininfo" },
          { id: '9-7', title: "Logs", route: "/admin/logs" }
        ]
      }
    ],
  ];
  
  

  export const industries = [
    'Aerospace and Defense',
    'Automotive',
    'Banking',
    'Biotechnology',
    'Chemical',
    'Construction',
    'Consumer Electronics',
    'Education',
    'Energy',
    'Entertainment',
    'Fashion',
    'Financial Services',
    'Food and Beverage',
    'Healthcare',
    'Information Technology',
    'Insurance',
    'Manufacturing',
    'Media',
    'Mining',
    'Pharmaceuticals',
    'Real Estate',
    'Retail',
    'Telecommunications',
    'Transportation',
    'Utilities',
    'Accounting',
    'Advertising',
    'Agriculture',
    'Architecture',
    'Automotive Repair',
    'Aviation',
    'Beauty and Cosmetics',
    'Broadcasting',
    'Computer Games',
    'Computer Hardware',
    'Computer Software',
    'Consulting',
    'Consumer Goods',
    'Courier Services',
    'E-commerce',
    'Education Management',
    'Electrical/Electronic Manufacturing',
    'Facilities Services',
    'Farming',
    'Financial Planning',
    'Fishery',
    'Fundraising',
    'Furniture',
    'Glass, Ceramics & Concrete',
    'Government Administration',
    'Graphic Design',
    'Higher Education',
    'Hospitality',
    'Human Resources',
    'Individual and Family Services',
    'Industrial Automation',
    'Information Services',
    'Information Technology and Services',
    'Insurance',
    'International Trade and Development',
    'Internet',
    'Investment Banking',
    'Judiciary',
    'Law Enforcement',
    'Legal Services',
    'Leisure, Travel & Tourism',
    'Libraries',
    'Logistics and Supply Chain',
    'Luxury Goods & Jewelry',
    'Machinery',
    'Management Consulting',
    'Maritime',
    'Marketing and Advertising',
    'Market Research',
    'Mechanical or Industrial Engineering',
    'Medical Devices',
    'Medical Practice',
    'Mining & Metals',
    'Nonprofit Organization Management',
    'Nursing',
    'Oil & Energy',
    'Online Media',
    'Outsourcing/Offshoring',
    'Package/Freight Delivery',
    'Packaging and Containers',
    'Paper & Forest Products',
    'Performing Arts',
    'Pharmaceuticals',
    'Photography',
    'Plastics',
    'Political Organization',
    'Primary/Secondary Education',
    'Printing',
    'Professional Training',
    'Program Development',
    'Public Relations',
    'Public Safety',
    'Publishing',
    'Railroad Manufacture',
    'Ranching',
    'Real Estate',
    'Religious Institutions',
    'Renewables & Environment',
    'Research',
    'Restaurants',
    'Retail',
    'Security and Investigations',
    'Semiconductors',
    'Shipbuilding',
    'Sporting Goods',
    'Sports',
    'Staffing and Recruiting',
    'Supermarkets',
    'Telecommunications',
    'Textiles',
    'Think Tanks',
    'Tobacco',
    'Translation and Localization',
    'Transportation/Trucking/Railroad',
    'Utilities',
    'Venture Capital',
    'Veterinary',
    'Warehousing',
    'Wholesale',
    'Wine and Spirits',
    'Wireless',
    'Writing and Editing',
    'Others',
    'Media',
    'Streaming',
    'OTT',
    'Gaming'
  ];
  
export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, North',
  'Korea, South',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];


export const customerDefault = {
  "name": "",
  "email": "",
  "phone": "",
  "website": "",
  "customerUserId": "",
  "vendor": false,
  "state": "",
  "location": "",
  "country": "",
  "identificationNumbers": [
    {
      "type": "",
      "number": ""
    }
  ],
  "password": "",
  "shippingAddress": "",
  "billingAddress": "",
  "storeUser": "",
  "individual": "",
  "category": "",
  "active": true,
  "bankDetails": [
    {
      "accountNumber": "",
      "bankName": "",
      "location": "",
      "IBAN": "",
      "swiftCode": "",
      "IFSC": ""
    }
  ],
  "language": "",
  "currency": ""
}

export const vendorDefault = {
  "name": "",
  "email": "",
  "phone": "",
  "website": "",
  "customerUserId": "",
  "vendor": true,
  "state": "",
  "location": "",
  "country": "",
  "identificationNumbers": [
    {
      "type": "",
      "number": ""
    }
  ],
  "gst": "",
  "shippingAddress": "",
  "billingAddress": "",
  "storeUser": false,
  "individual": false,
  "category": "",
  "active": true,
  "bankDetails": [
    {
      "accountNumber": "",
      "bankName": "",
      "location": "",
      "IBAN": "",
      "swiftCode": "",
      "IFSC": ""
    }
  ],
  "language": "",
  "currency": ""
}

export const colorDefault = {
  appId: '',
  mode: '',
  theme: {
    palette: {
      primary: {
        light: '',
        main: '',
        dark: '',
        contrastText: ''
      },
      secondary: {
        light: '',
        main: '',
        dark: '',
        contrastText: ''
      },
      error: {
        light: '',
        main: '',
        dark: '',
        contrastText: ''
      },
      warning: {
        light: '',
        main: '',
        dark: '',
        contrastText: ''
      },
      info: {
        light: '',
        main: '',
        dark: '',
        contrastText: ''
      },
      success: {
        light: '',
        main: '',
        dark: '',
        contrastText: ''
      },
      text: {
        primary: "",
        secondary: "",
        disabled: ""
      },
      background: {
        default: "",
        paper: ""
      },
      action: {
        active: "",
        hover: "",
        selected: "",
        disabled: "",
        disabledBackground: "",
        focus: ""
      },
      divider: ''
    }
  }
};


export const languages = [
  { name: 'Afrikaans', code: 'af' },
  { name: 'Albanian', code: 'sq' },
  { name: 'Amharic', code: 'am' },
  { name: 'Arabic', code: 'ar' },
  { name: 'Armenian', code: 'hy' },
  { name: 'Azerbaijani', code: 'az' },
  { name: 'Basque', code: 'eu' },
  { name: 'Belarusian', code: 'be' },
  { name: 'Bengali', code: 'bn' },
  { name: 'Bosnian', code: 'bs' },
  { name: 'Bulgarian', code: 'bg' },
  { name: 'Catalan', code: 'ca' },
  { name: 'Cebuano', code: 'ceb' },
  { name: 'Chinese (Simplified)', code: 'zh-CN' },
  { name: 'Chinese (Traditional)', code: 'zh-TW' },
  { name: 'Corsican', code: 'co' },
  { name: 'Croatian', code: 'hr' },
  { name: 'Czech', code: 'cs' },
  { name: 'Danish', code: 'da' },
  { name: 'Dutch', code: 'nl' },
  { name: 'English', code: 'en' },
  { name: 'Esperanto', code: 'eo' },
  { name: 'Estonian', code: 'et' },
  { name: 'Finnish', code: 'fi' },
  { name: 'French', code: 'fr' },
  { name: 'Galician', code: 'gl' },
  { name: 'Georgian', code: 'ka' },
  { name: 'German', code: 'de' },
  { name: 'Greek', code: 'el' },
  { name: 'Gujarati', code: 'gu' },
  { name: 'Haitian Creole', code: 'ht' },
  { name: 'Hausa', code: 'ha' },
  { name: 'Hawaiian', code: 'haw' },
  { name: 'Hebrew', code: 'he' },
  { name: 'Hindi', code: 'hi' },
  { name: 'Hmong', code: 'hmn' },
  { name: 'Hungarian', code: 'hu' },
  { name: 'Icelandic', code: 'is' },
  { name: 'Igbo', code: 'ig' },
  { name: 'Indonesian', code: 'id' },
  { name: 'Irish', code: 'ga' },
  { name: 'Italian', code: 'it' },
  { name: 'Japanese', code: 'ja' },
  { name: 'Javanese', code: 'jv' },
  { name: 'Kannada', code: 'kn' },
  { name: 'Kazakh', code: 'kk' },
  { name: 'Khmer', code: 'km' },
  { name: 'Kinyarwanda', code: 'rw' },
  { name: 'Korean', code: 'ko' },
  { name: 'Kurdish', code: 'ku' },
  { name: 'Kyrgyz', code: 'ky' },
  { name: 'Lao', code: 'lo' },
  { name: 'Latin', code: 'la' },
  { name: 'Latvian', code: 'lv' },
  { name: 'Lithuanian', code: 'lt' },
  { name: 'Luxembourgish', code: 'lb' },
  { name: 'Macedonian', code: 'mk' },
  { name: 'Malagasy', code: 'mg' },
  { name: 'Malay', code: 'ms' },
  { name: 'Malayalam', code: 'ml' },
  { name: 'Maltese', code: 'mt' },
  { name: 'Maori', code: 'mi' },
  { name: 'Marathi', code: 'mr' },
  { name: 'Mongolian', code: 'mn' },
  { name: 'Myanmar (Burmese)', code: 'my' },
  { name: 'Nepali', code: 'ne' },
  { name: 'Norwegian', code: 'no' },
  { name: 'Nyanja (Chichewa)', code: 'ny' },
  { name: 'Odia (Oriya)', code: 'or' },
  { name: 'Pashto', code: 'ps' },
  { name: 'Persian', code: 'fa' },
  { name: 'Polish', code: 'pl' },
  { name: 'Portuguese', code: 'pt' },
  { name: 'Punjabi', code: 'pa' },
  { name: 'Romanian', code: 'ro' },
  { name: 'Russian', code: 'ru' },
  { name: 'Samoan', code: 'sm' },
  { name: 'Scots Gaelic', code: 'gd' },
  { name: 'Serbian', code: 'sr' },
  { name: 'Sesotho', code: 'st' },
  { name: 'Shona', code: 'sn' },
  { name: 'Sindhi', code: 'sd' },
  { name: 'Sinhala (Sinhalese)', code: 'si' },
  { name: 'Slovak', code: 'sk' },
  { name: 'Slovenian', code: 'sl' },
  { name: 'Somali', code: 'so' },
  { name: 'Spanish', code: 'es' },
  { name: 'Sundanese', code: 'su' },
  { name: 'Swahili', code: 'sw' },
  { name: 'Swedish', code: 'sv' },
  { name: 'Tagalog (Filipino)', code: 'tl' },
  { name: 'Tajik', code: 'tg' },
  { name: 'Tamil', code: 'ta' },
  { name: 'Tatar', code: 'tt' },
  { name: 'Telugu', code: 'te' },
  { name: 'Thai', code: 'th' },
  { name: 'Turkish', code: 'tr' },
  { name: 'Turkmen', code: 'tk' },
  { name: 'Ukrainian', code: 'uk' },
  { name: 'Urdu', code: 'ur' },
  { name: 'Uyghur', code: 'ug' },
  { name: 'Uzbek', code: 'uz' },
  { name: 'Vietnamese', code: 'vi' },
  { name: 'Welsh', code: 'cy' },
  { name: 'Xhosa', code: 'xh' },
  { name: 'Yiddish', code: 'yi' },
  { name: 'Yoruba', code: 'yo' },
  { name: 'Zulu', code: 'zu' }
];


export const stateCountryCurrencyMapping = {
  // USA
  'Alabama': { country: 'USA', currency: 'USD' },
  'Alaska': { country: 'USA', currency: 'USD' },
  'Arizona': { country: 'USA', currency: 'USD' },
  'Arkansas': { country: 'USA', currency: 'USD' },
  'California': { country: 'USA', currency: 'USD' },
  'Colorado': { country: 'USA', currency: 'USD' },
  'Connecticut': { country: 'USA', currency: 'USD' },
  'Delaware': { country: 'USA', currency: 'USD' },
  'Florida': { country: 'USA', currency: 'USD' },
  'Georgia': { country: 'USA', currency: 'USD' },
  'Hawaii': { country: 'USA', currency: 'USD' },
  'Idaho': { country: 'USA', currency: 'USD' },
  'Illinois': { country: 'USA', currency: 'USD' },
  'Indiana': { country: 'USA', currency: 'USD' },
  'Iowa': { country: 'USA', currency: 'USD' },
  'Kansas': { country: 'USA', currency: 'USD' },
  'Kentucky': { country: 'USA', currency: 'USD' },
  'Louisiana': { country: 'USA', currency: 'USD' },
  'Maine': { country: 'USA', currency: 'USD' },
  'Maryland': { country: 'USA', currency: 'USD' },
  'Massachusetts': { country: 'USA', currency: 'USD' },
  'Michigan': { country: 'USA', currency: 'USD' },
  'Minnesota': { country: 'USA', currency: 'USD' },
  'Mississippi': { country: 'USA', currency: 'USD' },
  'Missouri': { country: 'USA', currency: 'USD' },
  'Montana': { country: 'USA', currency: 'USD' },
  'Nebraska': { country: 'USA', currency: 'USD' },
  'Nevada': { country: 'USA', currency: 'USD' },
  'New Hampshire': { country: 'USA', currency: 'USD' },
  'New Jersey': { country: 'USA', currency: 'USD' },
  'New Mexico': { country: 'USA', currency: 'USD' },
  'New York': { country: 'USA', currency: 'USD' },
  'North Carolina': { country: 'USA', currency: 'USD' },
  'North Dakota': { country: 'USA', currency: 'USD' },
  'Ohio': { country: 'USA', currency: 'USD' },
  'Oklahoma': { country: 'USA', currency: 'USD' },
  'Oregon': { country: 'USA', currency: 'USD' },
  'Pennsylvania': { country: 'USA', currency: 'USD' },
  'Rhode Island': { country: 'USA', currency: 'USD' },
  'South Carolina': { country: 'USA', currency: 'USD' },
  'South Dakota': { country: 'USA', currency: 'USD' },
  'Tennessee': { country: 'USA', currency: 'USD' },
  'Texas': { country: 'USA', currency: 'USD' },
  'Utah': { country: 'USA', currency: 'USD' },
  'Vermont': { country: 'USA', currency: 'USD' },
  'Virginia': { country: 'USA', currency: 'USD' },
  'Washington': { country: 'USA', currency: 'USD' },
  'West Virginia': { country: 'USA', currency: 'USD' },
  'Wisconsin': { country: 'USA', currency: 'USD' },
  'Wyoming': { country: 'USA', currency: 'USD' },

  // Canada
  'Ontario': { country: 'Canada', currency: 'CAD' },
  'Quebec': { country: 'Canada', currency: 'CAD' },
  'British Columbia': { country: 'Canada', currency: 'CAD' },
  'Alberta': { country: 'Canada', currency: 'CAD' },
  'Manitoba': { country: 'Canada', currency: 'CAD' },
  'Saskatchewan': { country: 'Canada', currency: 'CAD' },
  'Nova Scotia': { country: 'Canada', currency: 'CAD' },
  'New Brunswick': { country: 'Canada', currency: 'CAD' },
  'Newfoundland and Labrador': { country: 'Canada', currency: 'CAD' },
  'Prince Edward Island': { country: 'Canada', currency: 'CAD' },
  'Northwest Territories': { country: 'Canada', currency: 'CAD' },
  'Yukon': { country: 'Canada', currency: 'CAD' },
  'Nunavut': { country: 'Canada', currency: 'CAD' },

  // Australia
  'New South Wales': { country: 'Australia', currency: 'AUD' },
  'Victoria': { country: 'Australia', currency: 'AUD' },
  'Queensland': { country: 'Australia', currency: 'AUD' },
  'Western Australia': { country: 'Australia', currency: 'AUD' },
  'South Australia': { country: 'Australia', currency: 'AUD' },
  'Tasmania': { country: 'Australia', currency: 'AUD' },
  'Australian Capital Territory': { country: 'Australia', currency: 'AUD' },
  'Northern Territory': { country: 'Australia', currency: 'AUD' },

  // India
  'Andhra Pradesh': { country: 'India', currency: 'INR' },
  'Arunachal Pradesh': { country: 'India', currency: 'INR' },
  'Assam': { country: 'India', currency: 'INR' },
  'Bihar': { country: 'India', currency: 'INR' },
  'Chhattisgarh': { country: 'India', currency: 'INR' },
  'Goa': { country: 'India', currency: 'INR' },
  'Gujarat': { country: 'India', currency: 'INR' },
  'Haryana': { country: 'India', currency: 'INR' },
  'Himachal Pradesh': { country: 'India', currency: 'INR' },
  'Jharkhand': { country: 'India', currency: 'INR' },
  'Karnataka': { country: 'India', currency: 'INR' },
  'Kerala': { country: 'India', currency: 'INR' },
  'Madhya Pradesh': { country: 'India', currency: 'INR' },
  'Maharashtra': { country: 'India', currency: 'INR' },
  'Manipur': { country: 'India', currency: 'INR' },
  'Meghalaya': { country: 'India', currency: 'INR' },
  'Mizoram': { country: 'India', currency: 'INR' },
  'Nagaland': { country: 'India', currency: 'INR' },
  'Odisha': { country: 'India', currency: 'INR' },
  'Punjab': { country: 'India', currency: 'INR' },
  'Rajasthan': { country: 'India', currency: 'INR' },
  'Sikkim': { country: 'India', currency: 'INR' },
  'Tamil Nadu': { country: 'India', currency: 'INR' },
  'Telangana': { country: 'India', currency: 'INR' },
  'Tripura': { country: 'India', currency: 'INR' },
  'Uttar Pradesh': { country: 'India', currency: 'INR' },
  'Uttarakhand': { country: 'India', currency: 'INR' },
  'West Bengal': { country: 'India', currency: 'INR' },
  'Andaman and Nicobar Islands': { country: 'India', currency: 'INR' },
  'Chandigarh': { country: 'India', currency: 'INR' },
  'Dadra and Nagar Haveli and Daman and Diu': { country: 'India', currency: 'INR' },
  'Lakshadweep': { country: 'India', currency: 'INR' },
  'Delhi': { country: 'India', currency: 'INR' },
  'Puducherry': { country: 'India', currency: 'INR' },
  'Jammu and Kashmir': { country: 'India', currency: 'INR' },
  'Ladakh': { country: 'India', currency: 'INR' },

  // China
  'Anhui': { country: 'China', currency: 'CNY' },
  'Beijing': { country: 'China', currency: 'CNY' },
  'Chongqing': { country: 'China', currency: 'CNY' },
  'Fujian': { country: 'China', currency: 'CNY' },
  'Gansu': { country: 'China', currency: 'CNY' },
  'Guangdong': { country: 'China', currency: 'CNY' },
  'Guangxi': { country: 'China', currency: 'CNY' },
  'Guizhou': { country: 'China', currency: 'CNY' },
  'Hainan': { country: 'China', currency: 'CNY' },
  'Hebei': { country: 'China', currency: 'CNY' },
  'Heilongjiang': { country: 'China', currency: 'CNY' },
  'Henan': { country: 'China', currency: 'CNY' },
  'Hubei': { country: 'China', currency: 'CNY' },
  'Hunan': { country: 'China', currency: 'CNY' },
  'Inner Mongolia': { country: 'China', currency: 'CNY' },
  'Jiangsu': { country: 'China', currency: 'CNY' },
  'Jiangxi': { country: 'China', currency: 'CNY' },
  'Jilin': { country: 'China', currency: 'CNY' },
  'Liaoning': { country: 'China', currency: 'CNY' },
  'Ningxia': { country: 'China', currency: 'CNY' },
  'Qinghai': { country: 'China', currency: 'CNY' },
  'Shaanxi': { country: 'China', currency: 'CNY' },
  'Shandong': { country: 'China', currency: 'CNY' },
  'Shanghai': { country: 'China', currency: 'CNY' },
  'Shanxi': { country: 'China', currency: 'CNY' },
  'Sichuan': { country: 'China', currency: 'CNY' },
  'Tianjin': { country: 'China', currency: 'CNY' },
  'Tibet': { country: 'China', currency: 'CNY' },
  'Xinjiang': { country: 'China', currency: 'CNY' },
  'Yunnan': { country: 'China', currency: 'CNY' },
  'Zhejiang': { country: 'China', currency: 'CNY' },
  'Hong Kong': { country: 'China', currency: 'HKD' },
  'Macau': { country: 'China', currency: 'MOP' },

  // Brazil
  'Acre': { country: 'Brazil', currency: 'BRL' },
  'Alagoas': { country: 'Brazil', currency: 'BRL' },
  'Amapá': { country: 'Brazil', currency: 'BRL' },
  'Amazonas': { country: 'Brazil', currency: 'BRL' },
  'Bahia': { country: 'Brazil', currency: 'BRL' },
  'Ceará': { country: 'Brazil', currency: 'BRL' },
  'Distrito Federal': { country: 'Brazil', currency: 'BRL' },
  'Espírito Santo': { country: 'Brazil', currency: 'BRL' },
  'Goiás': { country: 'Brazil', currency: 'BRL' },
  'Maranhão': { country: 'Brazil', currency: 'BRL' },
  'Mato Grosso': { country: 'Brazil', currency: 'BRL' },
  'Mato Grosso do Sul': { country: 'Brazil', currency: 'BRL' },
  'Minas Gerais': { country: 'Brazil', currency: 'BRL' },
  'Pará': { country: 'Brazil', currency: 'BRL' },
  'Paraíba': { country: 'Brazil', currency: 'BRL' },
  'Paraná': { country: 'Brazil', currency: 'BRL' },
  'Pernambuco': { country: 'Brazil', currency: 'BRL' },
  'Piauí': { country: 'Brazil', currency: 'BRL' },
  'Rio de Janeiro': { country: 'Brazil', currency: 'BRL' },
  'Rio Grande do Norte': { country: 'Brazil', currency: 'BRL' },
  'Rio Grande do Sul': { country: 'Brazil', currency: 'BRL' },
  'Rondônia': { country: 'Brazil', currency: 'BRL' },
  'Roraima': { country: 'Brazil', currency: 'BRL' },
  'Santa Catarina': { country: 'Brazil', currency: 'BRL' },
  'São Paulo': { country: 'Brazil', currency: 'BRL' },
  'Sergipe': { country: 'Brazil', currency: 'BRL' },
  'Tocantins': { country: 'Brazil', currency: 'BRL' },

  // Russia
  'Adygea': { country: 'Russia', currency: 'RUB' },
  'Altai Krai': { country: 'Russia', currency: 'RUB' },
  'Altai Republic': { country: 'Russia', currency: 'RUB' },
  'Amur Oblast': { country: 'Russia', currency: 'RUB' },
  'Arkhangelsk Oblast': { country: 'Russia', currency: 'RUB' },
  'Astrakhan Oblast': { country: 'Russia', currency: 'RUB' },
  'Bashkortostan': { country: 'Russia', currency: 'RUB' },
  'Belgorod Oblast': { country: 'Russia', currency: 'RUB' },
  'Bryansk Oblast': { country: 'Russia', currency: 'RUB' },
  'Buryatia': { country: 'Russia', currency: 'RUB' },
  'Chechen Republic': { country: 'Russia', currency: 'RUB' },
  'Chelyabinsk Oblast': { country: 'Russia', currency: 'RUB' },
  'Chukotka Autonomous Okrug': { country: 'Russia', currency: 'RUB' },
  'Chuvashia': { country: 'Russia', currency: 'RUB' },
  'Dagestan': { country: 'Russia', currency: 'RUB' },
  'Ingushetia': { country: 'Russia', currency: 'RUB' },
  'Irkutsk Oblast': { country: 'Russia', currency: 'RUB' },
  'Ivanovo Oblast': { country: 'Russia', currency: 'RUB' },
  'Jewish Autonomous Oblast': { country: 'Russia', currency: 'RUB' },
  'Kabardino-Balkaria': { country: 'Russia', currency: 'RUB' },
  'Kaliningrad Oblast': { country: 'Russia', currency: 'RUB' },
  'Kalmykia': { country: 'Russia', currency: 'RUB' },
  'Kaluga Oblast': { country: 'Russia', currency: 'RUB' },
  'Kamchatka Krai': { country: 'Russia', currency: 'RUB' },
  'Karachay-Cherkessia': { country: 'Russia', currency: 'RUB' },
  'Karelia': { country: 'Russia', currency: 'RUB' },
  'Kemerovo Oblast': { country: 'Russia', currency: 'RUB' },
  'Khabarovsk Krai': { country: 'Russia', currency: 'RUB' },
  'Khakassia': { country: 'Russia', currency: 'RUB' },
  'Khanty-Mansi Autonomous Okrug': { country: 'Russia', currency: 'RUB' },
  'Kirov Oblast': { country: 'Russia', currency: 'RUB' },
  'Komi': { country: 'Russia', currency: 'RUB' },
  'Kostroma Oblast': { country: 'Russia', currency: 'RUB' },
  'Krasnodar Krai': { country: 'Russia', currency: 'RUB' },
  'Krasnoyarsk Krai': { country: 'Russia', currency: 'RUB' },
  'Kurgan Oblast': { country: 'Russia', currency: 'RUB' },
  'Kursk Oblast': { country: 'Russia', currency: 'RUB' },
  'Leningrad Oblast': { country: 'Russia', currency: 'RUB' },
  'Lipetsk Oblast': { country: 'Russia', currency: 'RUB' },
  'Magadan Oblast': { country: 'Russia', currency: 'RUB' },
  'Mari El': { country: 'Russia', currency: 'RUB' },
  'Mordovia': { country: 'Russia', currency: 'RUB' },
  'Moscow': { country: 'Russia', currency: 'RUB' },
  'Moscow Oblast': { country: 'Russia', currency: 'RUB' },
  'Murmansk Oblast': { country: 'Russia', currency: 'RUB' },
  'Nenets Autonomous Okrug': { country: 'Russia', currency: 'RUB' },
  'Nizhny Novgorod Oblast': { country: 'Russia', currency: 'RUB' },
  'Novgorod Oblast': { country: 'Russia', currency: 'RUB' },
  'Novosibirsk Oblast': { country: 'Russia', currency: 'RUB' },
  'Omsk Oblast': { country: 'Russia', currency: 'RUB' },
  'Orenburg Oblast': { country: 'Russia', currency: 'RUB' },
  'Oryol Oblast': { country: 'Russia', currency: 'RUB' },
  'Penza Oblast': { country: 'Russia', currency: 'RUB' },
  'Perm Krai': { country: 'Russia', currency: 'RUB' },
  'Primorsky Krai': { country: 'Russia', currency: 'RUB' },
  'Pskov Oblast': { country: 'Russia', currency: 'RUB' },
  'Rostov Oblast': { country: 'Russia', currency: 'RUB' },
  'Ryazan Oblast': { country: 'Russia', currency: 'RUB' },
  'Saint Petersburg': { country: 'Russia', currency: 'RUB' },
  'Sakha': { country: 'Russia', currency: 'RUB' },
  'Sakhalin Oblast': { country: 'Russia', currency: 'RUB' },
  'Samara Oblast': { country: 'Russia', currency: 'RUB' },
  'Saratov Oblast': { country: 'Russia', currency: 'RUB' },
  'Smolensk Oblast': { country: 'Russia', currency: 'RUB' },
  'Stavropol Krai': { country: 'Russia', currency: 'RUB' },
  'Sverdlovsk Oblast': { country: 'Russia', currency: 'RUB' },
  'Tambov Oblast': { country: 'Russia', currency: 'RUB' },
  'Tatarstan': { country: 'Russia', currency: 'RUB' },
  'Tomsk Oblast': { country: 'Russia', currency: 'RUB' },
  'Tula Oblast': { country: 'Russia', currency: 'RUB' },
  'Tver Oblast': { country: 'Russia', currency: 'RUB' },
  'Tyumen Oblast': { country: 'Russia', currency: 'RUB' },
  'Tyva': { country: 'Russia', currency: 'RUB' },
  'Udmurtia': { country: 'Russia', currency: 'RUB' },
  'Ulyanovsk Oblast': { country: 'Russia', currency: 'RUB' },
  'Vladimir Oblast': { country: 'Russia', currency: 'RUB' },
  'Volgograd Oblast': { country: 'Russia', currency: 'RUB' },
  'Vologda Oblast': { country: 'Russia', currency: 'RUB' },
  'Voronezh Oblast': { country: 'Russia', currency: 'RUB' },
  'Yamalo-Nenets Autonomous Okrug': { country: 'Russia', currency: 'RUB' },
  'Yaroslavl Oblast': { country: 'Russia', currency: 'RUB' },
  'Zabaykalsky Krai': { country: 'Russia', currency: 'RUB' },

  // Germany
  'Baden-Württemberg': { country: 'Germany', currency: 'EUR' },
  'Bavaria': { country: 'Germany', currency: 'EUR' },
  'Berlin': { country: 'Germany', currency: 'EUR' },
  'Brandenburg': { country: 'Germany', currency: 'EUR' },
  'Bremen': { country: 'Germany', currency: 'EUR' },
  'Hamburg': { country: 'Germany', currency: 'EUR' },
  'Hesse': { country: 'Germany', currency: 'EUR' },
  'Lower Saxony': { country: 'Germany', currency: 'EUR' },
  'Mecklenburg-Vorpommern': { country: 'Germany', currency: 'EUR' },
  'North Rhine-Westphalia': { country: 'Germany', currency: 'EUR' },
  'Rhineland-Palatinate': { country: 'Germany', currency: 'EUR' },
  'Saarland': { country: 'Germany', currency: 'EUR' },
  'Saxony': { country: 'Germany', currency: 'EUR' },
  'Saxony-Anhalt': { country: 'Germany', currency: 'EUR' },
  'Schleswig-Holstein': { country: 'Germany', currency: 'EUR' },
  'Thuringia': { country: 'Germany', currency: 'EUR' },

  // UK
  'England': { country: 'United Kingdom', currency: 'GBP' },
  'Scotland': { country: 'United Kingdom', currency: 'GBP' },
  'Wales': { country: 'United Kingdom', currency: 'GBP' },
  'Northern Ireland': { country: 'United Kingdom', currency: 'GBP' },

  // France
  'Île-de-France': { country: 'France', currency: 'EUR' },
  'Provence-Alpes-Côte d\'Azur': { country: 'France', currency: 'EUR' },
  'Auvergne-Rhône-Alpes': { country: 'France', currency: 'EUR' },
  'Hauts-de-France': { country: 'France', currency: 'EUR' },
  'Brittany': { country: 'France', currency: 'EUR' },
  'Grand Est': { country: 'France', currency: 'EUR' },
  'Bourgogne-Franche-Comté': { country: 'France', currency: 'EUR' },
  'Occitanie': { country: 'France', currency: 'EUR' },
  'Nouvelle-Aquitaine': { country: 'France', currency: 'EUR' },
  'Centre-Val de Loire': { country: 'France', currency: 'EUR' },
  'Pays de la Loire': { country: 'France', currency: 'EUR' },
  'Normandy': { country: 'France', currency: 'EUR' },
  'Corsica': { country: 'France', currency: 'EUR' },
  'Overseas': { country: 'France', currency: 'EUR' },
  'Martinique': { country: 'France', currency: 'EUR' },
  'Guadeloupe': { country: 'France', currency: 'EUR' },
  'Réunion': { country: 'France', currency: 'EUR' },
  'French Guiana': { country: 'France', currency: 'EUR' },

  // Japan
  'Hokkaido': { country: 'Japan', currency: 'JPY' },
  'Aomori': { country: 'Japan', currency: 'JPY' },
  'Iwate': { country: 'Japan', currency: 'JPY' },
  'Miyagi': { country: 'Japan', currency: 'JPY' },
  'Akita': { country: 'Japan', currency: 'JPY' },
  'Yamagata': { country: 'Japan', currency: 'JPY' },
  'Fukushima': { country: 'Japan', currency: 'JPY' },
  'Ibaraki': { country: 'Japan', currency: 'JPY' },
  'Tochigi': { country: 'Japan', currency: 'JPY' },
  'Gunma': { country: 'Japan', currency: 'JPY' },
  'Saitama': { country: 'Japan', currency: 'JPY' },
  'Chiba': { country: 'Japan', currency: 'JPY' },
  'Tokyo': { country: 'Japan', currency: 'JPY' },
  'Kanagawa': { country: 'Japan', currency: 'JPY' },
  'Niigata': { country: 'Japan', currency: 'JPY' },
  'Toyama': { country: 'Japan', currency: 'JPY' },
  'Ishikawa': { country: 'Japan', currency: 'JPY' },
  'Fukui': { country: 'Japan', currency: 'JPY' },
  'Yamanashi': { country: 'Japan', currency: 'JPY' },
  'Nagano': { country: 'Japan', currency: 'JPY' },
  'Gifu': { country: 'Japan', currency: 'JPY' },
  'Shizuoka': { country: 'Japan', currency: 'JPY' },
  'Aichi': { country: 'Japan', currency: 'JPY' },
  'Mie': { country: 'Japan', currency: 'JPY' },
  'Shiga': { country: 'Japan', currency: 'JPY' },
  'Kyoto': { country: 'Japan', currency: 'JPY' },
  'Osaka': { country: 'Japan', currency: 'JPY' },
  'Hyogo': { country: 'Japan', currency: 'JPY' },
  'Nara': { country: 'Japan', currency: 'JPY' },
  'Wakayama': { country: 'Japan', currency: 'JPY' },
  'Tottori': { country: 'Japan', currency: 'JPY' },
  'Shimane': { country: 'Japan', currency: 'JPY' },
  'Okayama': { country: 'Japan', currency: 'JPY' },
  'Hiroshima': { country: 'Japan', currency: 'JPY' },
  'Yamaguchi': { country: 'Japan', currency: 'JPY' },
  'Tokushima': { country: 'Japan', currency: 'JPY' },
  'Kagawa': { country: 'Japan', currency: 'JPY' },
  'Ehime': { country: 'Japan', currency: 'JPY' },
  'Kochi': { country: 'Japan', currency: 'JPY' },
  'Fukuoka': { country: 'Japan', currency: 'JPY' },
  'Saga': { country: 'Japan', currency: 'JPY' },
  'Nagasaki': { country: 'Japan', currency: 'JPY' },
  'Kumamoto': { country: 'Japan', currency: 'JPY' },
  'Oita': { country: 'Japan', currency: 'JPY' },
  'Miyazaki': { country: 'Japan', currency: 'JPY' },
  'Kagoshima': { country: 'Japan', currency: 'JPY' },
  'Okinawa': { country: 'Japan', currency: 'JPY' },

  // USA
  'Alabama': { country: 'United States', currency: 'USD' },
  'Alaska': { country: 'United States', currency: 'USD' },
  'Arizona': { country: 'United States', currency: 'USD' },
  'Arkansas': { country: 'United States', currency: 'USD' },
  'California': { country: 'United States', currency: 'USD' },
  'Colorado': { country: 'United States', currency: 'USD' },
  'Connecticut': { country: 'United States', currency: 'USD' },
  'Delaware': { country: 'United States', currency: 'USD' },
  'Florida': { country: 'United States', currency: 'USD' },
  'Georgia': { country: 'United States', currency: 'USD' },
  'Hawaii': { country: 'United States', currency: 'USD' },
  'Idaho': { country: 'United States', currency: 'USD' },
  'Illinois': { country: 'United States', currency: 'USD' },
  'Indiana': { country: 'United States', currency: 'USD' },
  'Iowa': { country: 'United States', currency: 'USD' },
  'Kansas': { country: 'United States', currency: 'USD' },
  'Kentucky': { country: 'United States', currency: 'USD' },
  'Louisiana': { country: 'United States', currency: 'USD' },
  'Maine': { country: 'United States', currency: 'USD' },
  'Maryland': { country: 'United States', currency: 'USD' },
  'Massachusetts': { country: 'United States', currency: 'USD' },
  'Michigan': { country: 'United States', currency: 'USD' },
  'Minnesota': { country: 'United States', currency: 'USD' },
  'Mississippi': { country: 'United States', currency: 'USD' },
  'Missouri': { country: 'United States', currency: 'USD' },
  'Montana': { country: 'United States', currency: 'USD' },
  'Nebraska': { country: 'United States', currency: 'USD' },
  'Nevada': { country: 'United States', currency: 'USD' },
  'New Hampshire': { country: 'United States', currency: 'USD' },
  'New Jersey': { country: 'United States', currency: 'USD' },
  'New Mexico': { country: 'United States', currency: 'USD' },
  'New York': { country: 'United States', currency: 'USD' },
  'North Carolina': { country: 'United States', currency: 'USD' },
  'North Dakota': { country: 'United States', currency: 'USD' },
  'Ohio': { country: 'United States', currency: 'USD' },
  'Oklahoma': { country: 'United States', currency: 'USD' },
  'Oregon': { country: 'United States', currency: 'USD' },
  'Pennsylvania': { country: 'United States', currency: 'USD' },
  'Rhode Island': { country: 'United States', currency: 'USD' },
  'South Carolina': { country: 'United States', currency: 'USD' },
  'South Dakota': { country: 'United States', currency: 'USD' },
  'Tennessee': { country: 'United States', currency: 'USD' },
  'Texas': { country: 'United States', currency: 'USD' },
  'Utah': { country: 'United States', currency: 'USD' },
  'Vermont': { country: 'United States', currency: 'USD' },
  'Virginia': { country: 'United States', currency: 'USD' },
  'Washington': { country: 'United States', currency: 'USD' },
  'West Virginia': { country: 'United States', currency: 'USD' },
  'Wisconsin': { country: 'United States', currency: 'USD' },
  'Wyoming': { country: 'United States', currency: 'USD' }
};


export const subCategoryDefault = {
  subCategoryName: "",
  subCategoryType: "",
  category: ""
}

export const categoryDefault = {
    categoryName: "",
    categoryType: "",
    category: ""
}

export const productDefault = {
  "name": "",
  "description": "",
  "category": "",
  "subCategory": "",
  "brand": "",
  "subBrand": "",
  "stock": '',
  "images": [
    {
       "url": "https://example.com/image1.jpg",
      "altText": "Image 1"
    }
  ],
  "RFQ": false,
  "HSN": "",
  "model": "",
  "productCode": "",
  "notes": [],
  "variants": [],
  "active": true
}


export const varientDefault ={
  "name": "",
  "color": "",
  "size": "",
  "productId": "",
  "images": [
    {
      "url": "",
      "altText": ""
    }
  ],
  "notes": [
    {
      "name": "",
      "description": ""
    }
  ],
  "model": "",
  "RFQ": false,
  "HSN": "",
  "productCode": "",
  "active": true
}

export const teamDefault = {
  teamName: ""
};

export const brandDefault = {
  "name": "",
  "category": "",
  "active": true
};

export const subBrandDefault = {
  "subBrandName": "",
  "brandId": "",
  "active": true
};

export const employeeDefault = {
    name: "",
    userId: "",
    teamId: "",
    admin: "",
    superAdmin: "",
    designation: "",
    superior: "",
    address: "",
    passport: "",
    dateOfBirth: "",
    dateOfJoining: "",
    phoneNumber: "",
    activeUser: "",
    emergencyContact: [{ name: '', phone: '', relationship: '' }]
  
}

export const appDefault = {
  appType: '',
  title: '',
  active: true,
  settings: {
    geo: [],
    domain: [],
    language: []
  }
}

export const layoutDefault = {
  appId: "",
  font: [],
  logos: [],
  fontSize: {
    base: "",
    xs: "",
    sm: "",
    md: "",
    lg: ""
  }
}


