export const employeeData = [
    {
      id: 1,
      name: 'Esther Howard',
      position: "Sale's manager USA",
      transactions: 3490,
      rise: true,
      tasksCompleted: 3,
      imgId: 0,
    },
  
    {
      id: 2,
      name: 'Eleanor Pena',
      position: "Sale's manager Europe",
      transactions: 590,
      rise: false,
      tasksCompleted: 5,
      imgId: 2,
    },
  
    {
      id: 3,
      name: 'Robert Fox',
      position: "Sale's manager Asia",
      transactions: 2600,
      rise: true,
      tasksCompleted: 1,
      imgId: 3,
    },
  ];
  
  export  const Countrydata = [
    { name: 'USA', rise: true, value: 21942.83, id: 1 },
    { name: 'Ireland', rise: false, value: 19710.0, id: 2 },
    { name: 'Ukraine', rise: false, value: 12320.3, id: 3 },
    { name: 'Sweden', rise: true, value: 9725.0, id: 4 },
  ];
  export const segmentationData = [
    { c1: 'Not Specified', c2: '800', c3: '#363636', color: '#535353' },
    { c1: 'Male', c2: '441', c3: '#818bb1', color: '#595f77' },
    { c1: 'Female', c2: '233', c3: '#2c365d', color: '#232942' },
    { c1: 'Other', c2: '126', c3: '#334ed8', color: '#2c3051' },
  ];
  
  export const sidebarItems = [
    [
      { id: '0', title: 'Dashboard', notifications: false,route:"/",parent:"/" },
    ],
    [
      { id: '4', title: 'Customer', notifications: false,route:"/customer",parent:"/customer" },
      { id: '5', title: 'Contacts', notifications: false,route:"/contact", parent:"/contact"},
      { id: '6', title: 'Groups', notifications: false,route:"/group", parent:"/group"},
      { id: '7', title: 'Marketing', notifications: false,route:"/marketing",parent:"/marketing" },
    ],
  ];


  export const industries = [
    'Aerospace and Defense',
    'Automotive',
    'Banking',
    'Biotechnology',
    'Chemical',
    'Construction',
    'Consumer Electronics',
    'Education',
    'Energy',
    'Entertainment',
    'Fashion',
    'Financial Services',
    'Food and Beverage',
    'Healthcare',
    'Information Technology',
    'Insurance',
    'Manufacturing',
    'Media',
    'Mining',
    'Pharmaceuticals',
    'Real Estate',
    'Retail',
    'Telecommunications',
    'Transportation',
    'Utilities',
    'Accounting',
    'Advertising',
    'Agriculture',
    'Architecture',
    'Automotive Repair',
    'Aviation',
    'Beauty and Cosmetics',
    'Broadcasting',
    'Computer Games',
    'Computer Hardware',
    'Computer Software',
    'Consulting',
    'Consumer Goods',
    'Courier Services',
    'E-commerce',
    'Education Management',
    'Electrical/Electronic Manufacturing',
    'Facilities Services',
    'Farming',
    'Financial Planning',
    'Fishery',
    'Fundraising',
    'Furniture',
    'Glass, Ceramics & Concrete',
    'Government Administration',
    'Graphic Design',
    'Higher Education',
    'Hospitality',
    'Human Resources',
    'Individual and Family Services',
    'Industrial Automation',
    'Information Services',
    'Information Technology and Services',
    'Insurance',
    'International Trade and Development',
    'Internet',
    'Investment Banking',
    'Judiciary',
    'Law Enforcement',
    'Legal Services',
    'Leisure, Travel & Tourism',
    'Libraries',
    'Logistics and Supply Chain',
    'Luxury Goods & Jewelry',
    'Machinery',
    'Management Consulting',
    'Maritime',
    'Marketing and Advertising',
    'Market Research',
    'Mechanical or Industrial Engineering',
    'Medical Devices',
    'Medical Practice',
    'Mining & Metals',
    'Nonprofit Organization Management',
    'Nursing',
    'Oil & Energy',
    'Online Media',
    'Outsourcing/Offshoring',
    'Package/Freight Delivery',
    'Packaging and Containers',
    'Paper & Forest Products',
    'Performing Arts',
    'Pharmaceuticals',
    'Photography',
    'Plastics',
    'Political Organization',
    'Primary/Secondary Education',
    'Printing',
    'Professional Training',
    'Program Development',
    'Public Relations',
    'Public Safety',
    'Publishing',
    'Railroad Manufacture',
    'Ranching',
    'Real Estate',
    'Religious Institutions',
    'Renewables & Environment',
    'Research',
    'Restaurants',
    'Retail',
    'Security and Investigations',
    'Semiconductors',
    'Shipbuilding',
    'Sporting Goods',
    'Sports',
    'Staffing and Recruiting',
    'Supermarkets',
    'Telecommunications',
    'Textiles',
    'Think Tanks',
    'Tobacco',
    'Translation and Localization',
    'Transportation/Trucking/Railroad',
    'Utilities',
    'Venture Capital',
    'Veterinary',
    'Warehousing',
    'Wholesale',
    'Wine and Spirits',
    'Wireless',
    'Writing and Editing',
    'Others',
    'Media',
    'Streaming',
    'OTT',
    'Gaming'
  ];
  
export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea, North',
  'Korea, South',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];


export const customerDefault = {
  name: '',
  email: '',
  address: '',
  website: '',
  state: '',
  category: '',
  location: '',
  country: '',
  pan: '',
  gst: ''
}

export const categoryDefault = {
  
}



